name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:
env:
  # Setting an environment variable with the value of a configuration variable
  NEXT_PUBLIC_VIDEO_SAS_URL: ${{ vars.NEXT_PUBLIC_VIDEO_SAS_URL }}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5

      - name: Install dependencies
        run: npm ci

      - name: Build and export static site
        env:
          # Signals Next.js to set basePath/assetPrefix for project pages
          GITHUB_PAGES: "true"
        run: |
          npm run build
          # Prevent Jekyll from interfering with static assets
          touch packages/site/out/.nojekyll

      - name: Mirror output into repository subfolder
        shell: bash
        run: |
          set -euo pipefail
          REPO_NAME="${GITHUB_REPOSITORY##*/}"
          if [ -z "${REPO_NAME}" ]; then
            echo "Unable to detect repository name from GITHUB_REPOSITORY"
            exit 1
          fi
          cd packages/site/out
          rm -rf "${REPO_NAME}"
          mkdir "${REPO_NAME}"
          find . -mindepth 1 -maxdepth 1 ! -name "${REPO_NAME}" -exec cp -R {} "${REPO_NAME}/" \;

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: packages/site/out

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
